version: '2'
services:
  mongo:
    image: mongo
    restart: always
    expose:
      - 27017
    volumes:
      - ./mongo-data:/data/db
  
  node-pubchem:
    build: ./node-pubchem
    restart: always
    privileged: true
    ports:
      - 3001:80
    depends_on:
      - mongo
    volumes:
      - ../node-pubchem/src:/git/node-pubchem/src