version: '2'
services:
  mongo:
    image: mongo:4
    restart: always
    expose:
      - 27017
    volumes:
      - ./mongo-data:/data/db
  
  node-pubchem-import:
    build: ./node-pubchem
    restart: always
    privileged: true
    depends_on:
      - mongo
    volumes:
#      - ../node-pubchem/src:/git/node-pubchem/src  # only for debug and change source code
      - ./originalData:/git/node-pubchem/originalData
    command: npm run cron

  node-pubchem:
    build: ./node-pubchem
    restart: always
    ports:
      - 3001:80
    depends_on:
      - mongo
#    volumes:
#      - ../node-pubchem/src:/git/node-pubchem/src

